services:
  mysqlcore.db:
    image: mysql:8.3
    ports:
      - 33066:3306
    env_file:
      - env/docker-env/mysql-db.dev.env
      - env/docker-env/mysql-user.dev.env
    volumes:
      - mysqlcore_vol:/var/lib/mysql
    networks:
      - mysqlcore_network
    
  mysqlcore.api:
    # image: preetbasson/mysqlcore-api:latest
    image: mysqlcore-api:latest
    build:
      context: .
      dockerfile: src/MySQLCore.API/Dockerfile
    ports:
      - 7840:7840
    env_file:
      - env/docker-env/mysql-user.dev.env
      - env/docker-env/mysqlcore-certificate.dev.env
      - env/docker-env/mysqlcore-api.dev.env
      - env/docker-env/mysqlcore-apikey.dev.env
    restart: always
    depends_on:
      - mysqlcore.db
    networks:
      - mysqlcore_network
    volumes:
      - /home/preet/Downloads/test/certs/aspnetcore.pfx:/https/aspnetcore.pfx:ro  # Mount the cert
volumes:
  mysqlcore_vol:

networks:
  mysqlcore_network:
    name: mysqlcore_network
    external: true
      
