services:
  mysqlcore.db:
    image: mysql:8.3
    ports:
      - 33066:3306
    env_file:
      - ${MYSQL_DB}
      - ${MYSQL_USER}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    networks:
      - mysqlcore_network
    
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - env/docker-env/rabbitmq-middleware.dev.env
    volumes:
      - ${RABBITMQ_DATA_PATH}:/var/lib/rabbitmq
    networks:
      - mysqlcore_network

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    volumes:
      - ${SEQ_PATH}:/data
    networks:
      - mysqlcore_network

  mysqlcore.api:
    image: mysqlcore-api:latest
    build:
      context: .
      dockerfile: src/MySQLCore.API/Dockerfile
    ports:
      - 5820:5820
    env_file:
      - ${MYSQL_USER}
      - ${APP_SETTINGS}
      - ${APP_APIKEY}
      - ${APP_CERT}
      - ${RABBITMQ}
    restart: always
    depends_on:
      - mysqlcore.db
      - rabbitmq
      - seq
    networks:
      - mysqlcore_network
    volumes:
      - ${APP_PATH}:/Logs
      # - ${CERTICATE_PATH}:/https/aspnetcore.pfx:ro  # Mount the cert

  mysqlcore.worker:
    image: mysqlcore-worker:latest
    build:
      context: .
      dockerfile: worker/MySQLCore.Worker/Dockerfile
    env_file:
      - ${MYSQL_USER}
      - ${APP_SETTINGS}
      - ${RABBITMQ}
    depends_on:
      - mysqlcore.db
      - rabbitmq
      - otel-collector
    networks:
      - mysqlcore_network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ${PROMETHEUS}:/etc/prometheus/prometheus.yml
      # - ${PROMETHEUS_DATA_PATH}:/prometheus
    networks:
      - mysqlcore_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ${GRAFANA_PATH}:/var/lib/grafana
    networks:
      - mysqlcore_network

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ${TEMPO}:/etc/tempo.yml
      # - ${TEMPO_DATA_PATH}:/tmp/tempo
    networks:
      - mysqlcore_network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector.yml"]
    ports:
      - "4319:4317"
      - "4320:4318"
    volumes:
      - ${OTEL_COLLECTOR}:/etc/otel-collector.yml
    depends_on:
      - tempo
    networks:
      - mysqlcore_network

volumes:
  mysqlcore_vol:

networks:
  mysqlcore_network:
    name: mysqlcore_network
    external: true
      
