services:
  mysqlcore.db:
    image: mysql:8.3
    ports:
      - 33066:3306
    env_file:
      - env/docker-env/dev-mysql-db.env
    volumes:
      - mysqlcore_vol:/var/lib/mysql
    networks:
      - mysqlcore_network
    
  mysqlcore.api:
    # image: preetbasson/mysqlcore-api:latest
    image: mysqlcore-api:latest
    build:
      context: .
      dockerfile: src/MySQLCore.API/Dockerfile
    ports:
      - 5840:5840
    env_file:
      - env/docker-env/dev-mysqlcore-api.env
      - env/docker-env/dev-mysqlcore-apikey.env
      - env/docker-env/dev-mysql-user.env
    restart: always
    depends_on:
      - mysqlcore.db
    networks:
      - mysqlcore_network

volumes:
  mysqlcore_vol:

networks:
  mysqlcore_network:
    name: mysqlcore_network
    external: true
      
