services:
  mysqlcore.db:
    image: mysql:8.3
    ports:
      - 33066:3306
    env_file:
      - env/docker-env/mysql-db.dev.env
      - env/docker-env/mysql-user.dev.env
    volumes:
      - /home/preet/Projects/Projects-Y/DatabaseStorage/Test:/var/lib/mysql
      # - mysqlcore_vol:/var/lib/mysql
    networks:
      - mysqlcore_network
    
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - env/docker-env/rabbitmq-middleware.dev.env
    networks:
      - mysqlcore_network

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    volumes:
      - /home/preet/Projects/Projects-Y/Logs/Seq:/data
    networks:
      - mysqlcore_network

  mysqlcore.api:
    image: mysqlcore-api:latest
    build:
      context: .
      dockerfile: src/MySQLCore.API/Dockerfile
    ports:
      - 5820:5820
    env_file:
      - env/docker-env/mysql-user.dev.env
      - env/docker-env/app-cert.dev.env
      - env/docker-env/app-settings.dev.env
      - env/docker-env/app-apikey.dev.env
      - env/docker-env/rabbitmq-settings.dev.env
    restart: always
    depends_on:
      - mysqlcore.db
      - rabbitmq
      - seq
    networks:
      - mysqlcore_network
    volumes:
      - /home/preet/Projects/Projects-Y/Logs/MySQLCore:/Logs
      # - /home/preet/Downloads/test/certs/aspnetcore.pfx:/https/aspnetcore.pfx:ro  # Mount the cert

volumes:
  mysqlcore_vol:

networks:
  mysqlcore_network:
    name: mysqlcore_network
    external: true
      
