apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: mysqlcore-app
  type: LoadBalancer
  ports:
    - port: 5840
      targetPort: 5840
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlcore-app-deployment
spec:
  selector:
    matchLabels:
      app: mysqlcore-app
      tier: backend
  template:
    metadata:
      labels:
        app: mysqlcore-app
        tier: backend
    spec:
      containers:
      - name: mysqlcore-node
        image: preetbasson/mysqlcore-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
          name: dev-secrets
