apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlcore-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlcore-worker
  template:
    metadata:
      labels:
        app: mysqlcore-worker
        tier: backend
    spec:
      containers:
      - name: mysqlcore-worker
        image: mysqlcore-worker:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: mysqlcore-configmap-dev
              key: core_environment
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysqlcore-configmap-dev
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mysqlcore-configmap-dev
              key: db_port
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysqlcore-configmap-dev
              key: mysql_database
        - name: MYSQL_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: mysqlcore-secret-dev
              key: mysql_root_user
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlcore-secret-dev
              key: mysql_root_password
        - name: RabbitMQ__UserName
          valueFrom:
            secretKeyRef:
              name: mysqlcore-secret-dev
              key: rabbitmq_user
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: mysqlcore-secret-dev
              key: rabbitmq_password
        - name: RabbitMQ__QueueName
          valueFrom:
            configMapKeyRef:
              name: mysqlcore-configmap-dev
              key: rabbitmq_queue_name
        - name: RabbitMQ__DeadLetterQueueName
          valueFrom:
            configMapKeyRef:
              name: mysqlcore-configmap-dev
              key: rabbitmq_dead_letter_queue_name
        - name: RabbitMQ__MaxRetryCount
          valueFrom:
            configMapKeyRef:
              name: mysqlcore-configmap-dev
              key: rabbitmq_max_retry_count
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector:4317
