global using AutoFixture;
global using Microsoft.Extensions.Logging;
global using Moq;
global using MySQLCore.API.Controllers;
global using MySQLCore.Core.Interfaces.Services;
global using MySQLCore.Core.Models.DTOs;
global using MySQLCore.Core.Models.DTOs.ImageDTOs;
global using MySQLCore.Core.Test.Helpers;
global using Xunit;
