apiVersion: v1
kind: Service
metadata:
  name: seq
spec:
  selector:
    app: seq
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
spec:
  selector:
    matchLabels:
      app: seq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
      - name: seq
        image: datalust/seq:latest
        ports:
        - containerPort: 80
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SEQ_FIRSTRUN_NOAUTHENTICATION
          value: "true"
        volumeMounts:
        - name: seq-persistent-storage
          mountPath: /data
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
      volumes:
      - name: seq-persistent-storage
        persistentVolumeClaim:
          claimName: seq-pvc
