global using FluentValidation;
global using Microsoft.Extensions.Logging;
global using MySQLCore.Core.Constants;
global using MySQLCore.Core.Interfaces.Messager;
global using MySQLCore.Core.Interfaces.Repos;
global using MySQLCore.Core.Interfaces.Services;
global using MySQLCore.Core.Messager;
global using MySQLCore.Core.Models.DTOs;
global using MySQLCore.Core.Models.DTOs.ImageDTOs;
