global using AutoFixture;
global using Microsoft.EntityFrameworkCore;
global using MySQLCore.Core.Models.DTOs;
global using MySQLCore.Core.Test.Helpers;
global using MySQLCore.Infrastructure.Context;
global using MySQLCore.Infrastructure.Entities.Tables;
global using MySQLCore.Infrastructure.Entities.Tables.ImageTables;
global using MySQLCore.Infrastructure.Repos;
global using Xunit;
