name: Docker Image CI
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: my-image-name:latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . --file ./src/MySQLCore.API/Dockerfile --tag $IMAGE_NAME

      - name: Save Docker image
        run: docker save $IMAGE_NAME -o my-image.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-image.tar
